# Generated by Django 6.0.4 on 2026-05-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Aviso"),
                            ("error", "Erro"),
                            ("importacao", "Importação"),
                            ("exportacao", "Exportação"),
                            ("acesso", "Acesso"),
                            ("seguranca", "Segurança"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("acao", models.CharField(max_length=300)),
                ("detalhes", models.JSONField(blank=True, null=True)),
                ("ip_origem", models.GenericIPAddressField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Log do Sistema",
                "verbose_name_plural": "Logs do Sistema",
                "db_table": "logs_sistema",
                "ordering": ["-criado_em"],
            },
        ),
    ]

