# Generated by Django 6.0.4 on 2026-05-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemListaExportada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf_exportado", models.CharField(max_length=14)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Item Exportado",
                "verbose_name_plural": "Itens Exportados",
                "db_table": "itens_lista_exportada",
            },
        ),
        migrations.CreateModel(
            name="ListaExportada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_lista", models.CharField(max_length=500)),
                ("filtros_utilizados", models.JSONField(default=dict)),
                ("quantidade_cpfs", models.IntegerField(default=0)),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("txt", "TXT"),
                            ("csv", "CSV"),
                            ("xlsx", "XLSX"),
                            ("clipboard", "Área de Transferência"),
                        ],
                        max_length=15,
                    ),
                ),
                ("com_pontuacao", models.BooleanField(default=False)),
                ("arquivo_gerado", models.CharField(blank=True, max_length=500)),
                ("exportado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lista Exportada",
                "verbose_name_plural": "Listas Exportadas",
                "db_table": "listas_exportadas",
                "ordering": ["-exportado_em"],
            },
        ),
    ]

