# Generated by Django 6.0.4 on 2026-05-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exportacao", "0001_initial"),
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemlistaexportada",
            name="pessoa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens_exportados",
                to="pessoas.pessoa",
            ),
        ),
    ]

