# Generated by Django 6.0.4 on 2026-05-01 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exportacao", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listaexportada",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exportacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemlistaexportada",
            name="lista_exportada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="exportacao.listaexportada",
            ),
        ),
        migrations.AddIndex(
            model_name="itemlistaexportada",
            index=models.Index(
                fields=["pessoa"], name="itens_lista_pessoa__d5205a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemlistaexportada",
            index=models.Index(
                fields=["lista_exportada"], name="itens_lista_lista_e_de57a8_idx"
            ),
        ),
    ]

