# Generated by Django 6.0.4 on 2026-05-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("convenios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseImportada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_arquivo", models.CharField(max_length=500)),
                ("caminho_origem", models.CharField(blank=True, max_length=1000)),
                ("quantidade_registros", models.IntegerField(default=0)),
                ("quantidade_validos", models.IntegerField(default=0)),
                ("quantidade_invalidos", models.IntegerField(default=0)),
                ("quantidade_duplicados", models.IntegerField(default=0)),
                ("data_importacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status_importacao",
                    models.CharField(
                        choices=[
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("parcial", "Parcial"),
                            ("erro", "Erro"),
                        ],
                        default="processando",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("mapeamento_colunas", models.JSONField(blank=True, null=True)),
                ("erros_detalhados", models.JSONField(blank=True, null=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bases",
                        to="convenios.convenio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Importada",
                "verbose_name_plural": "Bases Importadas",
                "db_table": "bases_importadas",
                "ordering": ["-data_importacao"],
            },
        ),
    ]

