# Generated by Django 6.0.4 on 2026-05-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("convenios", "0001_initial"),
        ("importacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=300, null=True)),
                ("cpf", models.CharField(db_index=True, max_length=11, unique=True)),
                ("cpf_valido", models.BooleanField(default=False)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("idade_calculada", models.SmallIntegerField(blank=True, null=True)),
                (
                    "cidade",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, null=True
                    ),
                ),
                (
                    "uf",
                    models.CharField(
                        blank=True, db_index=True, max_length=2, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
                "db_table": "pessoas",
                "indexes": [
                    models.Index(
                        fields=["cidade", "uf"], name="pessoas_cidade_6c096d_idx"
                    ),
                    models.Index(
                        fields=["idade_calculada"], name="pessoas_idade_c_658b19_idx"
                    ),
                    models.Index(
                        fields=["cpf_valido"], name="pessoas_cpf_val_d974c4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PessoaBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linha_original", models.IntegerField(blank=True, null=True)),
                ("dados_originais", models.JSONField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "base_importada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoas_base",
                        to="importacao.baseimportada",
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="convenios.convenio",
                    ),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bases",
                        to="pessoas.pessoa",
                    ),
                ),
                (
                    "regiao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="convenios.regiao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa × Base",
                "verbose_name_plural": "Pessoas × Bases",
                "db_table": "pessoa_base",
                "unique_together": {("pessoa", "base_importada")},
            },
        ),
    ]

