# Generated by Django 6.0.4 on 2026-05-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_convenio", models.CharField(max_length=150, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Convênio",
                "verbose_name_plural": "Convênios",
                "db_table": "convenios",
                "ordering": ["nome_convenio"],
            },
        ),
        migrations.CreateModel(
            name="Regiao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_regiao", models.CharField(max_length=150)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="regioes",
                        to="convenios.convenio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Região",
                "verbose_name_plural": "Regiões",
                "db_table": "regioes",
                "ordering": ["convenio", "nome_regiao"],
                "unique_together": {("nome_regiao", "convenio")},
            },
        ),
    ]

